version: '2'
services:
    myprop-app:
        image: myprop
        external_links:
            - myprop-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/myprop
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myprop-postgresql:
        extends:
            file: postgresql.yml
            service: myprop-postgresql
