version: '2'
services:
    myprop-app:
        image: myprop
        external_links:
            - myprop-postgresql:postgresql
            - myprop-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/myprop
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    myprop-postgresql:
        extends:
            file: postgresql.yml
            service: myprop-postgresql
    myprop-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: myprop-elasticsearch
